obj-$(CONFIG_OPENTHREAD) += platform/alarm.o
obj-$(CONFIG_OPENTHREAD) += platform/flash.o
obj-$(CONFIG_OPENTHREAD) += platform/logging.o
obj-$(CONFIG_OPENTHREAD) += platform/misc.o
obj-$(CONFIG_OPENTHREAD) += platform/platform.o
obj-$(CONFIG_OPENTHREAD) += platform/radio.o
obj-$(CONFIG_OPENTHREAD) += platform/random.o
obj-$(CONFIG_OPENTHREAD) += platform/spi.o
obj-$(CONFIG_OPENTHREAD) += platform/uart.o

subdir-ccflags-$(CONFIG_OPENTHREAD) += -I$(O)/openthread/platform
subdir-ccflags-$(CONFIG_OPENTHREAD) += -I$(O)/openthread/include
